function par = packParameters(p)
% PACKPARAMETERS  Convert parameter structure to numeric vector
% used by the dynamic model D_matrix, G_vector, etc.

par = [ ...
    p.m1, ...
    p.m2, ...
    p.mT, ...
    p.l1, ...
    p.l2, ...
    p.lt, ...
    p.I1, ...
    p.I2, ...
    p.IT, ...
    p.g ];
end
