function out1 = P_st(in1)
%P_st
%    OUT1 = P_st(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Jul-2026 12:10:30

theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
theta4 = in1(4,:);
theta5 = in1(5,:);
t2 = cos(theta3);
t3 = cos(theta4);
t4 = cos(theta5);
t5 = sin(theta3);
t6 = sin(theta4);
t7 = sin(theta5);
t8 = t2.*t3;
t9 = t2.*t6;
t10 = t3.*t5;
t11 = t5.*t6;
t12 = -t11;
t13 = t9+t10;
t14 = t8+t12;
out1 = [t9.*(-1.0./2.0)-t10./2.0+theta1-(t4.*t13)./2.0-(t7.*t14)./2.0+1.0;t8.*(-1.0./2.0)+t11./2.0-theta2-(t4.*t14)./2.0+(t7.*t13)./2.0+3.0./2.0];
