function [z_opt, out] = ch3_col_solve_min(p, z0)
%CH3_COL_SOLVE_MIN  Minimal repro of the core fmincon call in ch3_col_solve.

if nargin < 2 || isempty(z0)
    z0 = ch3_col_seed(p);
end

N = (numel(z0) - 1 - p.ny*p.n_ctrl) / p.nx;
[lb, ub] = ch3_col_bounds(p, N);

options = optimoptions('fmincon', ...
    'Algorithm',            'sqp', ...
    'Display',              'iter', ...
    'MaxIterations',        p.max_iter, ...
    'MaxFunctionEvaluations', p.max_fun_evals, ...
    'FiniteDifferenceType', 'central', ...
    'ScaleProblem',         false);

[z_opt, fval, exitflag, output] = fmincon( ...
    @(z) ch3_col_cost(z, p), z0, [], [], [], [], lb, ub, ...
    @(z) ch3_col_constraints(z, p), options);

[X, T, alpha] = ch3_col_unpack(z_opt, p);

out = struct('fval', fval, 'exitflag', exitflag, 'output', output, ...
             'alpha', alpha, 'X', X, 'T', T);
end