function DM = DM(in1)
%DM
%    DM = DM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    28-Jun-2026 21:18:38

Dq3 = in1(6,:);
q3 = in1(3,:);
t2 = cos(q3);
t3 = sin(q3);
t4 = Dq3.*t2.*(1.5e+1./4.0);
t5 = Dq3.*t3.*(1.5e+1./4.0);
t6 = -t5;
DM = reshape([0.0,0.0,t6,0.0,0.0,t4,t6,t4,0.0],[3,3]);
