function G = G(in1)
%G
%    G = G(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    22-Jun-2026 14:00:14

theta3 = in1(3,:);
theta4 = in1(4,:);
theta5 = in1(5,:);
theta6 = in1(6,:);
theta7 = in1(7,:);
t2 = theta3+theta4;
t3 = theta3+theta6;
t4 = sin(t2);
t5 = sin(t3);
t6 = t2+theta5;
t7 = t3+theta7;
t8 = sin(t6);
t9 = sin(t7);
t10 = t4.*3.677325e+1;
t11 = t5.*3.677325e+1;
t12 = t8.*1.225775e+1;
t13 = t9.*1.225775e+1;
G = [0.0;-2.94186e+2;t10+t11+t12+t13-sin(theta3).*3.677325e+1;t10+t12;t12;t11+t13;t13];
