function G = G(in1)
%G
%    G = G(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    28-Jun-2026 21:18:39

theta3 = in1(3,:);
G = [0.0;-9.8062e+1;sin(theta3).*(-3.677325e+1)];
