function G = G_m30(in1)
%G_M30  G of the 30 kg model this repository used before 2026-09-02.
%
%   Restored verbatim from git (commit 854f00b~1, generated 05-Jul-2026 by
%   rabbit_energy_model_generalized_Lagrange.m with torso 10 kg and four 5 kg
%   leg links, the same geometry as today). Only the function name differs.
%   The 74 kg regeneration (854f00b) changed masses and inertias alone, and
%   M, V and G are linear in those, so ch3_mvg can blend this model with the
%   current one exactly: see p.model_blend in ch3_params.
%
%   DO NOT EDIT; it is generated code.

%G
%    G = G(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-Jul-2026 10:58:44

theta3 = in1(3,:);
theta4 = in1(4,:);
theta5 = in1(5,:);
theta6 = in1(6,:);
theta7 = in1(7,:);
t2 = theta3+theta4;
t3 = theta3+theta6;
t4 = sin(t2);
t5 = sin(t3);
t6 = t2+theta5;
t7 = t3+theta7;
t8 = sin(t6);
t9 = sin(t7);
t10 = t4.*3.677325e+1;
t11 = t5.*3.677325e+1;
t12 = t8.*1.225775e+1;
t13 = t9.*1.225775e+1;
G = [0.0;-2.94186e+2;t10+t11+t12+t13-sin(theta3).*3.677325e+1;t10+t12;t12;t11+t13;t13];
