function Gsym = G_scale300(in1)
%G_scale300
%    Gsym = G_scale300(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    09-Sep-2026 13:31:47

theta3 = in1(3,:);
theta4 = in1(4,:);
theta5 = in1(5,:);
theta6 = in1(6,:);
theta7 = in1(7,:);
t2 = theta3+theta4;
t3 = theta3+theta6;
t4 = sin(t2);
t5 = sin(t3);
t6 = t2+theta5;
t7 = t3+theta7;
t8 = sin(t6);
t9 = sin(t7);
t10 = t4.*1.2502905e+2;
t11 = t5.*1.2502905e+2;
t12 = t8.*2.5741275e+1;
t13 = t9.*2.5741275e+1;
Gsym = [0.0;-2.1769764e+3;t10+t11+t12+t13-sin(theta3).*5.185028250000001e+2;t10+t12;t12;t11+t13;t13];
end
