function Gsym = G_scale050(in1)
%G_scale050
%    Gsym = G_scale050(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    09-Sep-2026 13:30:19

theta3 = in1(3,:);
theta4 = in1(4,:);
theta5 = in1(5,:);
theta6 = in1(6,:);
theta7 = in1(7,:);
t2 = theta3+theta4;
t3 = theta3+theta6;
t4 = sin(t2);
t5 = sin(t3);
t6 = t2+theta5;
t7 = t3+theta7;
t8 = sin(t6);
t9 = sin(t7);
t12 = t4.*2.0838175e+1;
t13 = t5.*2.0838175e+1;
t10 = t8.*4.2902125;
t11 = t9.*4.2902125;
Gsym = [0.0;-3.628294e+2;t10+t11+t12+t13-sin(theta3).*8.641713750000001e+1;t10+t12;t10;t11+t13;t11];
end
