function Gsym = G_scale070(in1)
%G_scale070
%    Gsym = G_scale070(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    09-Sep-2026 13:30:48

theta3 = in1(3,:);
theta4 = in1(4,:);
theta5 = in1(5,:);
theta6 = in1(6,:);
theta7 = in1(7,:);
t2 = theta3+theta4;
t3 = theta3+theta6;
t4 = sin(t2);
t5 = sin(t3);
t6 = t2+theta5;
t7 = t3+theta7;
t8 = sin(t6);
t9 = sin(t7);
t12 = t4.*2.9173445e+1;
t13 = t5.*2.9173445e+1;
t10 = t8.*6.0062975;
t11 = t9.*6.0062975;
Gsym = [0.0;-5.0796116e+2;t10+t11+t12+t13-sin(theta3).*1.209839925e+2;t10+t12;t10;t11+t13;t11];
end
