function G = G_vector(in1,in2)
%G_vector
%    G = G_vector(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-May-2026 12:59:30

g = in2(:,10);
l1 = in2(:,4);
l2 = in2(:,5);
lt = in2(:,6);
m1 = in2(:,1);
m2 = in2(:,2);
mT = in2(:,3);
q1 = in1(4,:);
q2 = in1(5,:);
q3 = in1(6,:);
q4 = in1(7,:);
qt = in1(3,:);
t2 = q1+qt;
t3 = q3+qt;
t4 = q2+t2;
t5 = q4+t3;
t6 = sin(t2);
t7 = sin(t3);
t8 = sin(t4);
t9 = sin(t5);
t10 = l1.*t6;
t11 = l1.*t7;
t12 = (l2.*t8)./2.0;
t13 = (l2.*t9)./2.0;
t14 = (g.*m1.*t10)./2.0;
t15 = (g.*m1.*t11)./2.0;
t16 = t10+t12;
t17 = t11+t13;
t18 = g.*m2.*t16;
t19 = g.*m2.*t17;
G = [0.0;g.*(m1.*2.0+m2.*2.0+mT);t14+t15+t18+t19-(g.*lt.*mT.*sin(qt))./2.0;t14+t18;g.*m2.*t12;t15+t19;g.*m2.*t13];
