function J_st = J_stance(in1,in2)
%J_stance
%    J_st = J_stance(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-May-2026 17:08:21

l1 = in2(:,4);
l2 = in2(:,5);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = q3+q4;
t3 = cos(t2);
t4 = q5+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = sin(t4);
t8 = l1.*t3;
t9 = l1.*t5;
t10 = l2.*t6;
t11 = l2.*t7;
t12 = -t8;
t13 = -t10;
t14 = t9+t11;
t15 = t12+t13;
J_st = reshape([1.0,0.0,0.0,1.0,t15,t14,t15,t14,t13,t11,0.0,0.0,0.0,0.0],[2,7]);
