function J_st = J_st(in1)
%J_st
%    J_st = J_st(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    06-Jul-2026 14:32:03

q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = q3+q4;
t3 = cos(t2);
t4 = q5+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = sin(t4);
t8 = t3./2.0;
t9 = t5./2.0;
t10 = -t8;
t11 = t6./2.0;
t12 = t7./2.0;
t13 = -t11;
t14 = t9+t12;
t15 = t10+t13;
J_st = reshape([1.0,0.0,0.0,-1.0,t15,t14,t15,t14,t13,t12,0.0,0.0,0.0,0.0],[2,7]);
