function J_sw = J_sw(in1)
%J_sw
%    J_sw = J_sw(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    06-Jul-2026 14:32:03

q3 = in1(3,:);
q6 = in1(6,:);
q7 = in1(7,:);
t2 = q3+q6;
t3 = cos(t2);
t4 = q7+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = sin(t4);
t8 = t3./2.0;
t9 = t5./2.0;
t10 = -t8;
t11 = t6./2.0;
t12 = t7./2.0;
t13 = -t11;
t14 = t9+t12;
t15 = t10+t13;
J_sw = reshape([1.0,0.0,0.0,-1.0,t15,t14,0.0,0.0,0.0,0.0,t15,t14,t13,t12],[2,7]);
