function Jdotdq_sw = Jdotdq_swing(in1,in2,in3)
%Jdotdq_swing
%    Jdotdq_sw = Jdotdq_swing(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-May-2026 17:08:21

dq3 = in2(3,:);
dq6 = in2(6,:);
dq7 = in2(7,:);
l1 = in3(:,4);
l2 = in3(:,5);
q3 = in1(3,:);
q6 = in1(6,:);
q7 = in1(7,:);
t2 = q3+q6;
t3 = dq3.^2;
t4 = dq6.^2;
t5 = dq7.^2;
t6 = cos(t2);
t7 = q7+t2;
t8 = sin(t2);
t9 = cos(t7);
t10 = sin(t7);
Jdotdq_sw = [l1.*t3.*t8+l1.*t4.*t8+l2.*t3.*t10+l2.*t4.*t10+l2.*t5.*t10+dq3.*dq6.*l1.*t8.*2.0+dq3.*dq6.*l2.*t10.*2.0+dq3.*dq7.*l2.*t10.*2.0+dq6.*dq7.*l2.*t10.*2.0;l1.*t3.*t6+l1.*t4.*t6+l2.*t3.*t9+l2.*t4.*t9+l2.*t5.*t9+dq3.*dq6.*l1.*t6.*2.0+dq3.*dq6.*l2.*t9.*2.0+dq3.*dq7.*l2.*t9.*2.0+dq6.*dq7.*l2.*t9.*2.0];
