function Jdotdq_st = Jdotdq_st(in1,in2)
%Jdotdq_st
%    Jdotdq_st = Jdotdq_st(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    06-Jul-2026 14:32:03

dq3 = in2(3,:);
dq4 = in2(4,:);
dq5 = in2(5,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = q3+q4;
t3 = dq3.^2;
t4 = dq4.^2;
t5 = dq5.^2;
t6 = cos(t2);
t7 = q5+t2;
t8 = sin(t2);
t9 = cos(t7);
t10 = sin(t7);
Jdotdq_st = [(t3.*t8)./2.0+(t4.*t8)./2.0+(t3.*t10)./2.0+(t4.*t10)./2.0+(t5.*t10)./2.0+dq3.*dq4.*t8+dq3.*dq4.*t10+dq3.*dq5.*t10+dq4.*dq5.*t10;(t3.*t6)./2.0+(t4.*t6)./2.0+(t3.*t9)./2.0+(t4.*t9)./2.0+(t5.*t9)./2.0+dq3.*dq4.*t6+dq3.*dq4.*t9+dq3.*dq5.*t9+dq4.*dq5.*t9];
