function Jdotdq_sw = Jdotdq_sw(in1,in2)
%Jdotdq_sw
%    Jdotdq_sw = Jdotdq_sw(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    06-Jul-2026 14:32:03

dq3 = in2(3,:);
dq6 = in2(6,:);
dq7 = in2(7,:);
q3 = in1(3,:);
q6 = in1(6,:);
q7 = in1(7,:);
t2 = q3+q6;
t3 = dq3.^2;
t4 = dq6.^2;
t5 = dq7.^2;
t6 = cos(t2);
t7 = q7+t2;
t8 = sin(t2);
t9 = cos(t7);
t10 = sin(t7);
Jdotdq_sw = [(t3.*t8)./2.0+(t4.*t8)./2.0+(t3.*t10)./2.0+(t4.*t10)./2.0+(t5.*t10)./2.0+dq3.*dq6.*t8+dq3.*dq6.*t10+dq3.*dq7.*t10+dq6.*dq7.*t10;(t3.*t6)./2.0+(t4.*t6)./2.0+(t3.*t9)./2.0+(t4.*t9)./2.0+(t5.*t9)./2.0+dq3.*dq6.*t6+dq3.*dq6.*t9+dq3.*dq7.*t9+dq6.*dq7.*t9];
