function Jdotdq_st = Jdotdq_stance(in1,in2,in3)
%Jdotdq_stance
%    Jdotdq_st = Jdotdq_stance(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    06-Jun-2026 17:37:41

dq3 = in2(3,:);
dq4 = in2(4,:);
dq5 = in2(5,:);
l1 = in3(:,4);
l2 = in3(:,5);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = q3+q4;
t3 = dq3.^2;
t4 = dq4.^2;
t5 = dq5.^2;
t6 = cos(t2);
t7 = q5+t2;
t8 = sin(t2);
t9 = cos(t7);
t10 = sin(t7);
Jdotdq_st = [l1.*t3.*t8+l1.*t4.*t8+l2.*t3.*t10+l2.*t4.*t10+l2.*t5.*t10+dq3.*dq4.*l1.*t8.*2.0+dq3.*dq4.*l2.*t10.*2.0+dq3.*dq5.*l2.*t10.*2.0+dq4.*dq5.*l2.*t10.*2.0;l1.*t3.*t6+l1.*t4.*t6+l2.*t3.*t9+l2.*t4.*t9+l2.*t5.*t9+dq3.*dq4.*l1.*t6.*2.0+dq3.*dq4.*l2.*t9.*2.0+dq3.*dq5.*l2.*t9.*2.0+dq4.*dq5.*l2.*t9.*2.0];
