function M = M(in1)
%M
%    M = M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    21-Jun-2026 14:25:16

theta3 = in1(3,:);
theta4 = in1(4,:);
theta5 = in1(5,:);
theta6 = in1(6,:);
theta7 = in1(7,:);
t2 = cos(theta3);
t3 = cos(theta5);
t4 = cos(theta7);
t5 = sin(theta3);
t6 = theta3+theta4;
t7 = theta3+theta6;
t8 = cos(t6);
t9 = cos(t7);
t10 = sin(t6);
t11 = sin(t7);
t12 = t6+theta5;
t13 = t7+theta7;
t18 = t3.*(5.0./4.0);
t19 = t4.*(5.0./4.0);
t20 = t3.*(5.0./8.0);
t21 = t4.*(5.0./8.0);
t22 = t2.*(1.5e+1./4.0);
t23 = t5.*(1.5e+1./4.0);
t14 = cos(t12);
t15 = cos(t13);
t16 = sin(t12);
t17 = sin(t13);
t24 = -t23;
t25 = t8.*(1.5e+1./4.0);
t26 = t9.*(1.5e+1./4.0);
t27 = t10.*(1.5e+1./4.0);
t28 = t11.*(1.5e+1./4.0);
t37 = t18+2.7e+1./1.0e+1;
t38 = t19+2.7e+1./1.0e+1;
t39 = t20+2.9e+1./4.0e+1;
t40 = t21+2.9e+1./4.0e+1;
t29 = t14.*(5.0./4.0);
t30 = t15.*(5.0./4.0);
t31 = t16.*(5.0./4.0);
t32 = t17.*(5.0./4.0);
t33 = -t25;
t34 = -t26;
t35 = -t29;
t36 = -t30;
t41 = t27+t31;
t42 = t28+t32;
t43 = t33+t35;
t44 = t34+t36;
t45 = t24+t41+t42;
t46 = t22+t43+t44;
M = reshape([3.0e+1,0.0,t46,t43,t35,t44,t36,0.0,3.0e+1,t45,t41,t31,t42,t32,t46,t45,t18+t19+7.00625,t37,t39,t38,t40,t43,t41,t37,t37,t39,0.0,0.0,t35,t31,t39,t39,2.9e+1./4.0e+1,0.0,0.0,t44,t42,t38,0.0,0.0,t38,t40,t36,t32,t40,0.0,0.0,t40,2.9e+1./4.0e+1],[7,7]);
