function M = M(in1)
%M
%    M = M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    28-Jun-2026 21:18:38

theta3 = in1(3,:);
t2 = cos(theta3);
t3 = sin(theta3);
t4 = t2.*(1.5e+1./4.0);
t5 = t3.*(1.5e+1./4.0);
M = reshape([1.0e+1,0.0,t4,0.0,1.0e+1,t5,t4,t5,2.57e+2./1.6e+2],[3,3]);
