function Msym = M_scale070(in1)
%M_scale070
%    Msym = M_scale070(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    09-Sep-2026 13:30:29

theta3 = in1(3,:);
theta4 = in1(4,:);
theta5 = in1(5,:);
theta6 = in1(6,:);
theta7 = in1(7,:);
t2 = cos(theta3);
t3 = cos(theta5);
t4 = cos(theta7);
t5 = sin(theta3);
t6 = theta3+theta4;
t7 = theta3+theta6;
t8 = cos(t6);
t9 = cos(t7);
t10 = sin(t6);
t11 = sin(t7);
t12 = t6+theta5;
t13 = t7+theta7;
t18 = t3.*(4.9e+1./8.0e+1);
t19 = t4.*(4.9e+1./8.0e+1);
t20 = t3.*(4.9e+1./1.6e+2);
t21 = t4.*(4.9e+1./1.6e+2);
t26 = t2.*(9.87e+2./8.0e+1);
t27 = t5.*(9.87e+2./8.0e+1);
t14 = cos(t12);
t15 = cos(t13);
t16 = sin(t12);
t17 = sin(t13);
t22 = t8.*(1.19e+2./4.0e+1);
t23 = t9.*(1.19e+2./4.0e+1);
t24 = t10.*(1.19e+2./4.0e+1);
t25 = t11.*(1.19e+2./4.0e+1);
t40 = t20+2.02125e-1;
t41 = t21+2.02125e-1;
t42 = t18+1.392125;
t43 = t19+1.392125;
t28 = -t22;
t29 = -t23;
t30 = -t24;
t31 = -t25;
t32 = t14.*(4.9e+1./8.0e+1);
t33 = t15.*(4.9e+1./8.0e+1);
t34 = t16.*(4.9e+1./8.0e+1);
t35 = t17.*(4.9e+1./8.0e+1);
t36 = -t32;
t37 = -t33;
t38 = -t34;
t39 = -t35;
t44 = t30+t38;
t45 = t31+t39;
t46 = t28+t36;
t47 = t29+t37;
t48 = t26+t46+t47;
t49 = t27+t44+t45;
Msym = reshape([2.59e+2./5.0,0.0,t48,t46,t36,t47,t37,0.0,2.59e+2./5.0,t49,t44,t38,t45,t39,t48,t49,t18+t19+8.0688125,t42,t40,t43,t41,t46,t44,t42,t42,t40,0.0,0.0,t36,t38,t40,t40,2.02125e-1,0.0,0.0,t47,t45,t43,0.0,0.0,t43,t41,t37,t39,t41,0.0,0.0,t41,2.02125e-1],[7,7]);
end
