function Msym = M_scale050(in1)
%M_scale050
%    Msym = M_scale050(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    09-Sep-2026 13:29:56

theta3 = in1(3,:);
theta4 = in1(4,:);
theta5 = in1(5,:);
theta6 = in1(6,:);
theta7 = in1(7,:);
t2 = cos(theta3);
t3 = cos(theta5);
t4 = cos(theta7);
t5 = sin(theta3);
t6 = theta3+theta4;
t7 = theta3+theta6;
t8 = cos(t6);
t9 = cos(t7);
t10 = sin(t6);
t11 = sin(t7);
t12 = t6+theta5;
t13 = t7+theta7;
t18 = t3.*(7.0./1.6e+1);
t19 = t4.*(7.0./1.6e+1);
t20 = t3.*(7.0./3.2e+1);
t21 = t4.*(7.0./3.2e+1);
t22 = t2.*(1.41e+2./1.6e+1);
t23 = t5.*(1.41e+2./1.6e+1);
t14 = cos(t12);
t15 = cos(t13);
t16 = sin(t12);
t17 = sin(t13);
t24 = t8.*(1.7e+1./8.0);
t25 = t9.*(1.7e+1./8.0);
t26 = t10.*(1.7e+1./8.0);
t27 = t11.*(1.7e+1./8.0);
t40 = t20+1.44375e-1;
t41 = t21+1.44375e-1;
t42 = t18+9.94375e-1;
t43 = t19+9.94375e-1;
t28 = t14.*(7.0./1.6e+1);
t29 = t15.*(7.0./1.6e+1);
t30 = t16.*(7.0./1.6e+1);
t31 = t17.*(7.0./1.6e+1);
t32 = -t24;
t33 = -t25;
t34 = -t26;
t35 = -t27;
t36 = -t28;
t37 = -t29;
t38 = -t30;
t39 = -t31;
t44 = t34+t38;
t45 = t35+t39;
t46 = t32+t36;
t47 = t33+t37;
t48 = t22+t46+t47;
t49 = t23+t44+t45;
Msym = reshape([3.7e+1,0.0,t48,t46,t36,t47,t37,0.0,3.7e+1,t49,t44,t38,t45,t39,t48,t49,t18+t19+5.7634375,t42,t40,t43,t41,t46,t44,t42,t42,t40,0.0,0.0,t36,t38,t40,t40,1.44375e-1,0.0,0.0,t47,t45,t43,0.0,0.0,t43,t41,t37,t39,t41,0.0,0.0,t41,1.44375e-1],[7,7]);
end
