function Msym = M_scale150(in1)
%M_scale150
%    Msym = M_scale150(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    09-Sep-2026 13:30:58

theta3 = in1(3,:);
theta4 = in1(4,:);
theta5 = in1(5,:);
theta6 = in1(6,:);
theta7 = in1(7,:);
t2 = cos(theta3);
t3 = cos(theta5);
t4 = cos(theta7);
t5 = sin(theta3);
t6 = theta3+theta4;
t7 = theta3+theta6;
t8 = cos(t6);
t9 = cos(t7);
t10 = sin(t6);
t11 = sin(t7);
t12 = t6+theta5;
t13 = t7+theta7;
t18 = t3.*(2.1e+1./1.6e+1);
t19 = t4.*(2.1e+1./1.6e+1);
t20 = t3.*(2.1e+1./3.2e+1);
t21 = t4.*(2.1e+1./3.2e+1);
t22 = t2.*(4.23e+2./1.6e+1);
t23 = t5.*(4.23e+2./1.6e+1);
t14 = cos(t12);
t15 = cos(t13);
t16 = sin(t12);
t17 = sin(t13);
t24 = t8.*(5.1e+1./8.0);
t25 = t9.*(5.1e+1./8.0);
t26 = t10.*(5.1e+1./8.0);
t27 = t11.*(5.1e+1./8.0);
t40 = t20+4.33125e-1;
t41 = t21+4.33125e-1;
t42 = t18+2.983125;
t43 = t19+2.983125;
t28 = -t24;
t29 = -t25;
t30 = -t26;
t31 = -t27;
t32 = t14.*(2.1e+1./1.6e+1);
t33 = t15.*(2.1e+1./1.6e+1);
t34 = t16.*(2.1e+1./1.6e+1);
t35 = t17.*(2.1e+1./1.6e+1);
t36 = -t32;
t37 = -t33;
t38 = -t34;
t39 = -t35;
t44 = t30+t38;
t45 = t31+t39;
t46 = t28+t36;
t47 = t29+t37;
t48 = t22+t46+t47;
t49 = t23+t44+t45;
Msym = reshape([1.11e+2,0.0,t48,t46,t36,t47,t37,0.0,1.11e+2,t49,t44,t38,t45,t39,t48,t49,t18+t19+1.72903125e+1,t42,t40,t43,t41,t46,t44,t42,t42,t40,0.0,0.0,t36,t38,t40,t40,4.33125e-1,0.0,0.0,t47,t45,t43,0.0,0.0,t43,t41,t37,t39,t41,0.0,0.0,t41,4.33125e-1],[7,7]);
end
