function out1 = P_sw(in1)
%P_sw
%    OUT1 = P_sw(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-Jul-2026 10:58:34

theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
theta6 = in1(6,:);
theta7 = in1(7,:);
t2 = cos(theta3);
t3 = cos(theta6);
t4 = cos(theta7);
t5 = sin(theta3);
t6 = sin(theta6);
t7 = sin(theta7);
t8 = t2.*t3;
t9 = t2.*t6;
t10 = t3.*t5;
t11 = t5.*t6;
t12 = -t11;
t13 = t9+t10;
t14 = t8+t12;
out1 = [t9.*(-1.0./2.0)-t10./2.0+theta1-(t4.*t13)./2.0-(t7.*t14)./2.0;t8.*(-1.0./2.0)+t11./2.0-theta2-(t4.*t14)./2.0+(t7.*t13)./2.0];
