function T_w1 = T1(in1)
%T1
%    T_w1 = T1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    19-Jun-2026 20:18:43

theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
theta4 = in1(4,:);
t2 = cos(theta3);
t3 = cos(theta4);
t4 = sin(theta3);
t5 = sin(theta4);
t6 = t2.*t3;
t7 = t2.*t5;
t8 = t3.*t4;
t9 = t4.*t5;
t10 = -t7;
t11 = -t8;
t12 = t10+t11;
T_w1 = reshape([t6-t9,0.0,t12,0.0,t12,0.0,-t6+t9,0.0,0.0,1.0,0.0,0.0,theta1,0.0,theta2,1.0],[4,4]);
