function T_w3 = T3(in1)
%T3
%    T_w3 = T3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    30-Jun-2026 12:18:26

theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
theta6 = in1(6,:);
t2 = cos(theta3);
t3 = cos(theta6);
t4 = sin(theta3);
t5 = sin(theta6);
t6 = t2.*t3;
t7 = t2.*t5;
t8 = t3.*t4;
t9 = t4.*t5;
t10 = -t7;
t11 = -t8;
t12 = t10+t11;
T_w3 = reshape([t6-t9,0.0,t12,0.0,t12,0.0,-t6+t9,0.0,0.0,1.0,0.0,0.0,theta1+1.0,0.0,-theta2+3.0./2.0,1.0],[4,4]);
