function T_w4 = T4(in1)
%T4
%    T_w4 = T4(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    22-Jun-2026 13:51:34

theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
theta6 = in1(6,:);
theta7 = in1(7,:);
t2 = cos(theta3);
t3 = cos(theta6);
t4 = cos(theta7);
t5 = sin(theta3);
t6 = sin(theta6);
t7 = sin(theta7);
t8 = t2.*t3;
t9 = t2.*t6;
t10 = t3.*t5;
t11 = t5.*t6;
t12 = -t11;
t13 = t9+t10;
t14 = t8+t12;
t15 = t4.*t13;
t16 = t7.*t13;
t17 = t4.*t14;
t18 = -t15;
t19 = t7.*t14;
t20 = -t19;
t21 = t18+t20;
T_w4 = reshape([-t16+t17,0.0,t21,0.0,t21,0.0,t16-t17,0.0,0.0,1.0,0.0,0.0,t9.*(-1.0./2.0)-t10./2.0+theta1+1.0,0.0,t8.*(-1.0./2.0)+t11./2.0-theta2+3.0./2.0,1.0],[4,4]);
