function T_wt = Tt(in1)
%Tt
%    T_wt = Tt(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    19-Jun-2026 20:18:43

theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
t2 = cos(theta3);
t3 = sin(theta3);
t4 = -t3;
T_wt = reshape([t2,0.0,t4,0.0,t4,0.0,-t2,0.0,0.0,1.0,0.0,0.0,theta1,0.0,theta2,1.0],[4,4]);
