function V = V(in1)
%V
%    V = V(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    28-Jun-2026 21:18:39

omega1 = in1(4,:);
omega2 = in1(5,:);
omega3 = in1(6,:);
theta3 = in1(3,:);
t2 = conj(omega3);
t3 = cos(theta3);
t4 = sin(theta3);
t5 = omega3.^2;
V = [t4.*t5.*(-1.5e+1./4.0);t3.*t5.*(1.5e+1./4.0);omega3.*t3.*conj(omega2).*(-1.5e+1./8.0)+omega3.*t4.*conj(omega1).*(1.5e+1./8.0)-omega1.*omega3.*t4.*(1.5e+1./4.0)+omega2.*omega3.*t3.*(1.5e+1./4.0)+omega1.*t2.*t4.*(1.5e+1./8.0)-omega2.*t2.*t3.*(1.5e+1./8.0)];
