function Vsym = V_scale150(in1)
%V_scale150
%    Vsym = V_scale150(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    09-Sep-2026 13:31:16

omega3 = in1(10,:);
omega4 = in1(11,:);
omega5 = in1(12,:);
omega6 = in1(13,:);
omega7 = in1(14,:);
theta3 = in1(3,:);
theta4 = in1(4,:);
theta5 = in1(5,:);
theta6 = in1(6,:);
theta7 = in1(7,:);
t2 = sin(theta5);
t3 = sin(theta7);
t4 = theta3+theta4;
t5 = theta3+theta6;
t6 = omega3.*2.0;
t7 = omega3.^2;
t8 = omega4.^2;
t9 = omega5.^2;
t10 = omega6.^2;
t11 = omega7.^2;
t12 = cos(t4);
t13 = cos(t5);
t14 = sin(t4);
t15 = sin(t5);
t16 = t4+theta5;
t17 = t5+theta7;
t18 = cos(t16);
t19 = cos(t17);
t20 = sin(t16);
t21 = sin(t17);
t22 = t12.*(5.1e+1./8.0);
t23 = t13.*(5.1e+1./8.0);
t24 = t14.*(5.1e+1./8.0);
t25 = t15.*(5.1e+1./8.0);
t26 = t18.*(2.1e+1./1.6e+1);
t27 = t19.*(2.1e+1./1.6e+1);
t28 = t20.*(2.1e+1./1.6e+1);
t29 = t21.*(2.1e+1./1.6e+1);
t30 = t24+t28;
t31 = t25+t29;
t32 = t22+t26;
t33 = t23+t27;
mt1 = [t9.*t28+t8.*t30+t11.*t29+t10.*t31+t7.*(t30+t31-sin(theta3).*(4.23e+2./1.6e+1))+omega3.*omega5.*t20.*(2.1e+1./8.0)+omega4.*omega5.*t20.*(2.1e+1./8.0)+omega3.*omega7.*t21.*(2.1e+1./8.0)+omega6.*omega7.*t21.*(2.1e+1./8.0)+omega4.*t6.*t30+omega6.*t6.*t31;t9.*t18.*(-2.1e+1./1.6e+1)-t11.*t19.*(2.1e+1./1.6e+1)-t8.*t32-t10.*t33-t7.*(t32+t33-cos(theta3).*(4.23e+2./1.6e+1))-omega3.*omega5.*t18.*(2.1e+1./8.0)-omega4.*omega5.*t18.*(2.1e+1./8.0)-omega3.*omega7.*t19.*(2.1e+1./8.0)-omega6.*omega7.*t19.*(2.1e+1./8.0)-omega3.*omega4.*t32.*2.0-omega3.*omega6.*t33.*2.0];
mt2 = [t2.*t9.*(-2.1e+1./3.2e+1)-t3.*t11.*(2.1e+1./3.2e+1)-omega3.*omega5.*t2.*(2.1e+1./1.6e+1)-omega4.*omega5.*t2.*(2.1e+1./1.6e+1)-omega3.*omega7.*t3.*(2.1e+1./1.6e+1)-omega6.*omega7.*t3.*(2.1e+1./1.6e+1);omega5.*t2.*(omega4.*2.0+omega5+t6).*(-2.1e+1./3.2e+1);t2.*(omega3+omega4).^2.*(2.1e+1./3.2e+1);omega7.*t3.*(omega6.*2.0+omega7+t6).*(-2.1e+1./3.2e+1);t3.*(omega3+omega6).^2.*(2.1e+1./3.2e+1)];
Vsym = [mt1;mt2];
end
