function [f, g, aux] = ch3_control_affine(x, p)
%CH3_CONTROL_AFFINE  Stage 1: single-support dynamics as xdot = f(x) + g(x)u.
%
%   [f, g]      = ch3_control_affine(x, p)
%   [f, g, aux] = ch3_control_affine(x, p)
%
% Chapter 3 writes the continuous phase in control-affine form
%
%       xdot = f(x) + g(x) u ,      x = [q; dq]  (14x1),  u (4x1)
%
% and every later stage depends on that split: the Lie derivatives of stage 4
% are literally Jy*ddq_drift and Jy*ddq_in, and the stage-8 QP needs the
% ground reaction force to be AFFINE IN u to write the friction cone as a
% linear inequality.  So this function returns the split explicitly rather
% than just evaluating ddq for a given u.
%
% DERIVATION.  During single support the stance foot is pinned, giving the
% holonomic constraint P_st(q) = const, differentiated twice to
% J_st*ddq + Jdot*dq = 0.  With the contact wrench lambda as the multiplier,
%
%       [ M   -J' ] [ ddq    ]   [ B u - V - G ]
%       [ J    0  ] [ lambda ] = [   -Jdot*dq  ]
%
% The left-hand matrix does not depend on u, so ONE factorization with FIVE
% right-hand sides (one drift, four input directions) gives the entire affine
% structure exactly -- no finite differencing anywhere:
%
%       ddq    = ddq_drift + ddq_in * u
%       lambda = lam_drift + lam_in * u
%
% and therefore
%
%       f(x) = [ dq ; ddq_drift ]        g(x) = [ 0(7x4) ; ddq_in ]
%
% Inputs
%   x : 14x1 state [q; dq]
%   p : parameter struct from ch3_params (uses p.nq, p.nu)
%
% Outputs
%   f   : 14x1 drift vector field
%   g   : 14x4 input vector field
%   aux : struct with the pieces later stages reuse --
%           .ddq_drift 7x1   .ddq_in 7x4
%           .lam_drift 2x1   .lam_in 2x4   (ground reaction force [Fx; Fz],
%                                           world frame, z up-positive)
%           .M .Vv .Gv .J .Jdotdq  raw dynamics terms
%
% See also CH3_IO_LIN, CH3_GRF, CH3_IMPACT.

nq = p.nq;
nu = p.nu;

q  = x(1:nq);
dq = x(nq+1:2*nq);

% --- dynamics terms (generated by the Symbolic Math Toolbox, in Dynamics/) --
M_mat  = M(q);
V_vec  = V([q; dq]);
G_vec  = G(q);
B_mat  = input_matrix();

% --- stance contact -------------------------------------------------------
J      = J_st(q);          % 2x7
Jdotdq = Jdotdq_st(q, dq); % 2x1
nc     = size(J, 1);

% --- one KKT factorization, five right-hand sides -------------------------
A = [M_mat, -J.'; ...
     J,     zeros(nc)];

rhs = [ [-V_vec - G_vec], B_mat ; ...
        [-Jdotdq],        zeros(nc, nu) ];

sol = A \ rhs;             % (nq+nc) x (1+nu)

ddq_drift = sol(1:nq,      1);
ddq_in    = sol(1:nq,      2:end);
lam_drift = sol(nq+1:end,  1);
lam_in    = sol(nq+1:end,  2:end);

% --- assemble the vector fields ------------------------------------------
f = [dq;              ddq_drift];
g = [zeros(nq, nu);   ddq_in   ];

if nargout > 2
    aux = struct('ddq_drift', ddq_drift, 'ddq_in', ddq_in, ...
                 'lam_drift', lam_drift, 'lam_in', lam_in, ...
                 'M', M_mat, 'Vv', V_vec, 'Gv', G_vec, ...
                 'J', J, 'Jdotdq', Jdotdq);
end

end
